name: Demo trigger event

on:
  # Webhooks events
  push:
    branches:
     - main
     - feat/*
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened
      - closed
  # Schdule events
  schedule:
    - cron: 0 0 * * *
    - cron: 0 9 * * 0
  # Manual events
  workflow_dispatch:
    inputs:
      yourName:
        required: true
        default: My friend
      areyoufeelinggood:
        required: true
        type: boolean
      howdoyoufindGithubActions:
        required: false
        type: choice
        options:
          - Awesome
          - Okay
          - Naa

env:
  #Add any evnironment varaibles
  MY_NAME: Batman
  GREETING: Hello

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Step
        run: |
          echo Hello World!!! 
          echo I am Vengeance. I am the knight. I AM $GREETING $MY_NAME !!
  Greeting2:
    runs-on: ubuntu-latest
    env:
      GREETING: Good morning
      MY_NAME: David
    steps:
      - name: Greeting Step
        run: |
          echo Hello World!!!
          echo I am Vengeance. I am the knight. I AM $GREETING $MY_NAME !!
  Job2:
    runs-on: ubuntu-latest
    needs: [Greeting]
    steps:
      - name: Step2
        run: echo "${{ github.actor }} is learning Github Actions."
      - name: Step3
        run: echo "Great!"
        if: ${{inputs.areyoufeelinggood == false}}
      - name: Step4
        run: echo "Don't worry. I am here with you!!"
